services:
  postgres:
    image: postgres
    container_name: postgres_db
    networks:
      - vpoker-network
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    image: vpoker/backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  vpoker-network:
    name: vpoker-network
    driver: bridge

volumes:
  postgres-volume:
